---
:server_config: config/server.yml     # Import reads the storage config from a server.  Point this at the server config.
:schemata_path: ./resources/schemata    # Where to find .sql files for use as a schema
:notify: 12345                        # Update the UI once per n links
:create_db: true                      # Create the db if it doesn't already exist?
:logging:                       # Logging and output options
  :progname: Import               # What to call the app in logs
  :logs:                          # A list of log outputs
    :default:                       # Call this log "default"
      :dev: STDOUT                  # Where to log.  Give a filename, or use 'STDOUT' or 'STDERR'
      :level: :info                 # Level to log.  One of :debug, :warn, :info, :error, or :fatal
    #:errors:
      #:dev: 'logs/server.err'
      #:level: :warn                                              
    :file_log:
      :dev: 'logs/server.log'
      :level: :info

